### ISSUE TITLE
Character data should include their id

### ISSUE THREAD

**Issue by thomas-tcj** [genshindev/api#110]
Hey, I think it would be useful for the character data to include the identifier of the character.

This way, when parsing data from `https://api.genshin.dev/characters/all`, it would be possible to determine the URL for the icon of each character.

Happy to do it myself, if we can agree that this is a useful feature.

**Comment by JVO-sknife** [comment]
I agree, it's very hard to identify characters. For example, vision is added to name for Traveler and others are identified by their name.
In my opinion, Ids should be artificial and given in data. Anyway it would be very useful to include ids.

**Comment by LolnationCH** [comment]
I think it would be great, I had to make my own json file, and then I merged the two of them together.
Here it is if anyone want to use it (Had to put `.md` cause github don't want `.json`...)
[CharactersId.json.md](https://github.com/genshindev/api/files/7781904/CharactersId.json.md)

**Comment by xannem** [comment]
Also agree identifiers would be helpful, created PR with the ids: https://github.com/genshindev/api/pull/220
