### ISSUE TITLE
Character skins

### ISSUE THREAD

**Issue by MartiiDev** [genshindev/api#122]
Hey, your API seems nice but I thought about a little addition.
I think it would be nice for each character to have a list of their skins (if they have some) when you request the character's info:

Example for Keqing (since she will have a skin in 2.4)
`"skins":[{"name":"Opulent Splendor","image":"https://skin_img.png"},`

**Comment by Tainted06** [comment]
Great idea, I'll work on adding it right now. I'll add information about the name, description, rarity, and price. For the image, I'll add it how the other images are and name it outfit-outfitname. I'll also add the image name in the json data just to make it easier.

**Comment by man90es** [comment]
Looks like at least some outfits have been added to the data files. It there are any specific outfits still missing, please make a separate issue and/or PR
