### ISSUE TITLE
[Question] Public API load limits

### ISSUE THREAD

**Issue by muirch** [genshindev/api#125]
Hi 👋

Is there any limitations to usage of public api deployed on https://api.genshin.dev?

I plan to create something like _open source_ catalog web app based on data from your API with features like search, team builder and much more.

If this app will send requests based on the pages visited by users like search by name of hero or something like this, will I be penalized if it makes a heavy load on your server?

**Comment by LiterallyLink** [comment]
You should be caching a majority if not all of the data you’re fetching to avoid constant API calls.

**Comment by muirch** [comment]
> You should be caching a majority if not all of the data you’re fetching to avoid constant API calls.

I understand how to work with API to avoid constant calls, but caching all data in local storage seems not best case for me. I can use some libs for state management and call data only once when user opens the app, but it still can make heavy load if app will become popular and have much users => much calls. So will I be banned from API usage in this case or not, that's the question.

**Comment by NurMarvin** [comment]
The server the API is deployed on is rather durable so I don't intend on banning people for putting too heavy load on the API. If the API load becomes too much I will simply upgrade the infrastructure.
So no, you shouldn't fear getting banned from the API unless you manage to trigger some ban on Cloudflare's side as the API is proxied through it.
