### ISSUE TITLE
[request] generator build characters output image

### ISSUE THREAD

**Issue by hardianto02** [genshindev/api#130]
![Screenshot_2022-01-23-21-40-18-742_com whatsapp](https://user-images.githubusercontent.com/95894400/150681313-ba5bf62e-cc6a-42df-b332-d82ef6130ed8.jpg)

**Comment by man90es** [comment]
It's not clear what this issue was supposed to mean. Closing for now, please make a fresh issue with a more detailed description if it's something that still matters
