### ISSUE TITLE
[Request] Add Talent and Constellations Icon Picture

### ISSUE THREAD

**Issue by Stupid-Benz** [genshindev/api#134]
As the title mentioned.

**Comment by MukiA** [comment]
Would really appreciate if this could get added

**Comment by PSDat123** [comment]
working on it!

**Comment by man90es** [comment]
This has been implemented, images can be requested like this:
https://genshin.jmp.blue/characters/albedo/talent-na.png
https://genshin.jmp.blue/characters/albedo/talent-skill.png
https://genshin.jmp.blue/characters/albedo/talent-burst.png
https://genshin.jmp.blue/characters/albedo/talent-passive-0.png
https://genshin.jmp.blue/characters/albedo/talent-passive-1.png
https://genshin.jmp.blue/characters/albedo/talent-passive-2.png
https://genshin.jmp.blue/characters/albedo/constellation-1.png
https://genshin.jmp.blue/characters/albedo/constellation-2.png
https://genshin.jmp.blue/characters/albedo/constellation-3.png
https://genshin.jmp.blue/characters/albedo/constellation-4.png
https://genshin.jmp.blue/characters/albedo/constellation-5.png
https://genshin.jmp.blue/characters/albedo/constellation-6.png

If those images are missing for some of the characters, please create a separate issue and/or PR
