### ISSUE TITLE
Feature Request: Category Parameters

### ISSUE THREAD

**Issue by wumpus225** [genshindev/api#146]
It would be nice if we are able to grab data based on the parameters. For example, being able to grab all characters with a specific vision (e.g Geo) or the Star ratings for artifacts, characters, and weapons.

I mean it's possible to implement this feature but not at the moment i guess, as it needs a route rework for more structured paths. Correct me if I'm wrong.

**Comment by roose** [comment]
`https://api.genshin.dev/characters/all?vision_key=GEO&weapon_type=SWORD` etc.
