### ISSUE TITLE
Website out of sync

### ISSUE THREAD

**Issue by Glazelf** [genshindev/api#163]
Recently added changes like [Kuki Shinobu & Shikanoin Heizou](https://github.com/genshindev/api/commit/86df35b442a6516c46d191cc44f0ef10683cfc57) don't seem to be reflected on the [website](https://api.genshin.dev/).

**Comment by ChrisMGeo** [comment]
Any idea why this is the case? does the website not keep in track with the GitHub page?

**Comment by GerGerApex1** [comment]
I guess that the API needs to be restarted in the server.

**Comment by arktn** [comment]
> I guess that the API needs to be restarted in the server. *(To show new changes.)*

It does, all the changes are live now :)

@JMPJNS this issue can be closed.
