### ISSUE TITLE
Only 57 characters showable

### ISSUE THREAD

**Issue by scarajun** [genshindev/api#221]
It seems like are only 57 characters being showed in the API, even if it is updated with all the 71 playable characters.
Apparently the characters that received an update also don't have a path page.
The attachment files show it as in the Postman.
![image](https://github.com/genshindev/api/assets/141688540/f0c67309-1aee-4951-98f4-09a8d5a837d7)
![image](https://github.com/genshindev/api/assets/141688540/ca2f26b9-850e-4758-a7bc-e976ea82e54a)
![image](https://github.com/genshindev/api/assets/141688540/1809f8cf-fc73-4481-a935-12ef71a11b62)

**Comment by man90es** [comment]
If you're looking for an up-to-date version of the API, it's at https://genshin.jmp.blue/characters/alhaitham. The one listed in README.md hasn't received updates for a long time
