### ISSUE TITLE
[Bug] Inconsistent Naming with Fontaine Character Icons

### ISSUE THREAD

**Issue by Aokijiop** [genshindev/api#260]
The icons for various Fontaine characters are named "gatcha-card" and "gatcha-splash" but should be renamed to "gacha-card" and "gacha-splash" to be consistent with the rest of the characters.

**Comment by Thiru-kumaran-R** [comment]
can I solve this bug .

**Comment by Aokijiop** [comment]
Beat me to it 😆

**Comment by Thiru-kumaran-R** [comment]
No worries! Great minds think alike 😄
