### ISSUE TITLE
Missing images for multiple artifact sets

### ISSUE THREAD

**Issue by Malloks** [genshindev/api#298]
There are missing images for multiple artifact sets
- desert-pavilion-chronicle
- flower-of-paradise-lost
- nymph-s-dream
- prayers-for-destiny
- prayers-for-illumination
- prayers-for-wisdom
- prayers-for-firmament
- prayers-for-springtime
- vourukasha-s-glow

**Comment by keihachimaru** [comment]
I'll work on it.

**Comment by keihachimaru** [comment]
I've added every set except **prayers for firmament**, because afaik it doesn't exist, it is the dendro dropped boss circlet.
