### ISSUE TITLE
Missing data for weapon Sword of Narzissenkreuz

### ISSUE THREAD

**Issue by Malloks** [genshindev/api#299]
The data for the weapon "sword-of-narzissenkreuz" is missing when accessing it through the API https://genshin.jmp.blue/weapons/sword-of-narzissenkreuz - shows nothing
https://genshin.jmp.blue/weapons/sword-of-narzissenkreuz/icon - works though

**Comment by man90es** [comment]
@JMPJNS is investigating the problem with CI/CD

**Comment by man90es** [comment]
It's fixed now, thank you for reporting this
