### ISSUE TITLE
chili-minced-cornbread-buns multiple entries and misspelled

### ISSUE THREAD

**Issue by myun11** [genshindev/api#314]
https://genshin.jmp.blue/consumables/food/list

![6b49f4ebc3b02224244712666768f0b2](https://github.com/user-attachments/assets/8ce6d2ed-ee24-473e-94fc-185853c0bdaa)

**Comment by keihachimaru** [comment]
I was going to fix it, but after fetching origin and searching for the misspell I couldn't find it
![Captura de pantalla 2024-09-23 141310](https://github.com/user-attachments/assets/8b0df247-c7b2-43e2-adf2-2bc39df09c0c)

perhaps it has been fixed?

**Comment by man90es** [comment]
> I was going to fix it, but after fetching origin and searching for the misspell I couldn't find it ![Captura de pantalla 2024-09-23 141310](https://private-user-images.githubusercontent.com/175596440/369867265-8b0df247-c7b2-43e2-adf2-2bc39df09c0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNTA2MDYsIm5iZiI6MTcyNzI1MDMwNiwicGF0aCI6Ii8xNzU1OTY0NDAvMzY5ODY3MjY1LThiMGRmMjQ3LWM3YjItNDNlMi1hZGYyLTJiYzM5ZGYwOWMwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQwNzQ1MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzZjYTU0MmEzMjVlNDFiMDk2MTllZDEzNWI3MTAxNTNhYjliNjFkODg0YjY3MjQyZmJkOWJjYWIyZDE0M2ZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IWYemlvnopogQTw70LiXk97elVfvvxuotYUuSqt9FG8)
> 
> perhaps it has been fixed?

This PR refers to an extra image, not text data
