### ISSUE TITLE
Certain weapons have incorrect "location" field

### ISSUE THREAD

**Issue by Kiriot22** [genshindev/api#64]
The following weapons have their location set to `Gacha` despite not being obtainable from it, but rather from chests or npcs:

```
Amber Catalyst
Dark Iron Sword
Ebony Bow
Fillet Blade
Halberd
Otherworldly Story
Quartz
Skyrider Greatsword
Twin Nephrite
White Iron Greatsword
```

Also `Kunwu's Iris Rift` needs to be renamed to `Vortex Vanquisher`

**Comment by ghaku** [comment]
I checked over it and yeah you're right. I fixed these mistakes and will open a pullrequest now!

**Comment by JMPJNS** [comment]
can we close this issue?
