### ISSUE TITLE
Entity weapons/the-unforged for language en not found

### ISSUE THREAD

**Issue by nmMmnmMmn** [genshindev/api#93]
![image](https://user-images.githubusercontent.com/21982381/132664510-a3a9707f-7aa8-4800-9fdc-e0a6952c4c04.png)

But it's ok in jp
![image](https://user-images.githubusercontent.com/21982381/132665104-4ff862e7-cbe1-4ed1-ab3c-b80bf57299e6.png)

And currently the api lacks images of the unforged.

**Comment by NurMarvin** [comment]
Sorry, that one's on me! I recently moved the API from Railway to a personal server of mine, which shouldn't be an issue onto itself but my script that should have detected the change should have pulled the new commits from #91 and restarted the API but I made a little mistake which made it not work correctly.
This has been addressed though and shouldn't happen anymore in the future!
