### ISSUE TITLE
A lack of information for /characters endpoint

### ISSUE THREAD

**Issue by CuteShaun** [genshindev/api#94]
Guys, thanks for doing a great job! When I getting data from `https://api.genshin.dev/characters`, there are only characters' names, and what if somebody wants to make some filters or sorts by characters (elements, nation, rarity), etc. It seems we need an array of objects with all info about every character in general `/characters` request, not only in special like `/characters/albedo`

**Comment by NurMarvin** [comment]
That's already a thing! It's a bit hidden, I gotta admit, but there's an `/all` endpoint for all entity types, which also supports filtering. If you for example want all characters from Mondstadt, you can just use `/characters/all?nation=Mondstadt`. If you don't want any filtering, just use `/characters/all` with any query parameters.

**Comment by CuteShaun** [comment]
Thanks a bunch, hope we can add this info in documentation later :)
